name: cat_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # Router
  go_router: ^4.1.0

  # State Management
  flutter_riverpod: ^1.0.4

  # Graphic Dependencies
  flutter_svg: ^1.1.1+1
  shimmer: ^2.0.0
  animate_do: ^2.1.0
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.1.4
  flutter_native_splash: ^2.2.4

  # Utils Dependencies
  dio: ^4.0.6

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: '^0.9.2'

flutter:
  uses-material-design: true

  assets:
    - assets/i18n/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

flutter_native_splash:
  background_image: assets/images/splash_image.png
  android_12:
    background_image: assets/images/splash_image.png
  fullscreen: true

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/launcher_icon.png'
